# Generated by Django 5.2 on 2025-11-09 06:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(blank=True, help_text='Optional display name', max_length=255)),
                ('gender', models.CharField(blank=True, max_length=1)),
                ('degree', models.CharField(blank=True, max_length=50)),
                ('year', models.CharField(blank=True, help_text='Academic year', max_length=20)),
                ('department', models.CharField(blank=True, help_text='Department code', max_length=255)),
                ('rollno', models.CharField(blank=True, help_text='Student roll number', max_length=20)),
                ('phone_number', models.CharField(blank=True, max_length=15)),
                ('college_name', models.CharField(default='Rajalakshmi Engineering College', max_length=255)),
                ('profile_picture', models.URLField(blank=True, help_text='Social profile picture URL')),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_eventStaff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_qr_scanner', models.BooleanField(default=False, help_text='Can access QR scanner functionality')),
                ('is_verified', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
                'db_table': 'users_userprofile',
            },
        ),
    ]
