# Generated by Django 5.2.7 on 2025-10-27 05:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(help_text='Name of the event', max_length=200)),
                ('description', models.TextField(help_text='Detailed description of the event')),
                ('event_date', models.DateTimeField(help_text='Date and time of the event')),
                ('event_end_date', models.DateField(blank=True, help_text='End date of the event (for multi-day events)', null=True)),
                ('start_time', models.TimeField(blank=True, help_text='Start time of the event', null=True)),
                ('end_time', models.TimeField(blank=True, help_text='End time of the event', null=True)),
                ('event_type', models.CharField(choices=[('workshop', 'Workshop'), ('seminar', 'Seminar'), ('competition', 'Competition'), ('hackathon', 'Hackathon'), ('meetup', 'Meetup'), ('conference', 'Conference'), ('other', 'Other')], default='other', help_text='Type of event', max_length=20)),
                ('payment_type', models.CharField(choices=[('free', 'Free'), ('paid', 'Paid')], default='free', help_text='Whether the event is free or paid', max_length=10)),
                ('participation_type', models.CharField(choices=[('intra', 'Intra College'), ('inter', 'Inter College')], default='intra', help_text='Intra college or inter college event', max_length=10)),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text='Price for paid events (leave blank for free events)', max_digits=10, null=True)),
                ('max_participants', models.PositiveIntegerField(blank=True, help_text='Maximum number of participants (optional)', null=True)),
                ('registration_deadline', models.DateTimeField(blank=True, help_text='Last date for registration (optional)', null=True)),
                ('venue', models.CharField(blank=True, help_text='Event venue', max_length=200, null=True)),
                ('event_image', models.ImageField(blank=True, help_text='Event image file', null=True, upload_to='event_images/')),
                ('event_video', models.URLField(blank=True, help_text='Event video URL')),
                ('video_url', models.URLField(blank=True, help_text='Social media post URL (Instagram, Twitter, etc.)', null=True)),
                ('require_registration_form', models.BooleanField(default=False, help_text='Whether registration form with questions is required')),
                ('is_active', models.BooleanField(default=True, help_text='Whether the event is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'ordering': ['-event_date'],
            },
        ),
        migrations.CreateModel(
            name='EventGuide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('english', 'English'), ('hindi', 'Hindi'), ('tamil', 'Tamil'), ('english_hindi', 'English, Hindi'), ('english_tamil', 'English, Tamil'), ('all', 'All Languages')], default='english', help_text='Language(s) of the event', max_length=20)),
                ('duration', models.CharField(help_text="Duration of the event (e.g., '3 Days', '2 Hours')", max_length=50)),
                ('tickets_needed_for', models.CharField(help_text="Age requirement for tickets (e.g., '13 yrs & above')", max_length=50)),
                ('entry_allowed_for', models.CharField(choices=[('all_ages', 'All ages'), ('13_above', '13 yrs & above'), ('18_above', '18 yrs & above'), ('21_above', '21 yrs & above')], default='all_ages', help_text='Age restriction for entry', max_length=20)),
                ('layout', models.CharField(choices=[('indoor', 'Indoor'), ('outdoor', 'Outdoor'), ('hybrid', 'Hybrid')], default='indoor', help_text='Event layout/location type', max_length=10)),
                ('seating_arrangement', models.CharField(choices=[('standing', 'Standing'), ('seated', 'Seated'), ('mixed', 'Mixed')], default='seated', help_text='Seating arrangement', max_length=10)),
                ('venue', models.CharField(default='TBD', help_text='Event venue location', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='guide', to='event.event')),
            ],
            options={
                'verbose_name': 'Event Guide',
                'verbose_name_plural': 'Event Guides',
            },
        ),
        migrations.CreateModel(
            name='EventQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='Question text', max_length=255)),
                ('question_type', models.CharField(choices=[('short_text', 'Short Text'), ('long_text', 'Long Text'), ('email', 'Email'), ('phone', 'Phone Number'), ('number', 'Number'), ('date', 'Date'), ('single_choice', 'Single Choice'), ('multi_choice', 'Multiple Choice'), ('file', 'File Upload')], default='short_text', max_length=20)),
                ('required', models.BooleanField(default=True, help_text='Is this question mandatory?')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order')),
                ('help_text', models.CharField(blank=True, help_text='Helper text for the question', max_length=255)),
                ('options', models.JSONField(blank=True, help_text='Options for choice questions (list of strings)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='event.event')),
            ],
            options={
                'verbose_name': 'Event Question',
                'verbose_name_plural': 'Event Questions',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='confirmed', max_length=20)),
                ('payment_status', models.BooleanField(default=False)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('answers', models.JSONField(blank=True, default=list, help_text="User's answers to event questions")),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='event.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Event Participant',
                'verbose_name_plural': 'Event Participants',
                'ordering': ['-registered_at'],
            },
        ),
        migrations.CreateModel(
            name='ODList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_sent', models.BooleanField(default=False)),
                ('attendance', models.BooleanField(default=False)),
                ('hash', models.CharField(max_length=64, unique=True)),
                ('attendance_marked_at', models.DateTimeField(blank=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='od_lists', to='event.event')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registered_participants', to='event.participant')),
            ],
            options={
                'verbose_name': 'On Duty List Entry',
                'verbose_name_plural': 'On Duty List',
            },
        ),
        migrations.AddIndex(
            model_name='participant',
            index=models.Index(fields=['event', 'registration_status'], name='event_parti_event_i_7a8e3e_idx'),
        ),
        migrations.AddIndex(
            model_name='participant',
            index=models.Index(fields=['user', 'registered_at'], name='event_parti_user_id_f1d762_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='participant',
            unique_together={('user', 'event')},
        ),
        migrations.AlterUniqueTogether(
            name='odlist',
            unique_together={('participant',)},
        ),
    ]
