# Generated by Django 5.2.7 on 2025-11-02 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='gateway_credentials',
            field=models.JSONField(blank=True, help_text='Custom payment gateway credentials (JSON format)', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='gateway_options',
            field=models.CharField(blank=True, choices=[('payu', 'PayU'), ('cashfree', 'Cashfree')], help_text='Payment gateway to use for this event', max_length=20, null=True),
        ),
    ]
