# Generated by Django 5.2.7 on 2025-11-05 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_event_gateway_credentials_event_gateway_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_mode',
            field=models.CharField(choices=[('offline', 'Offline'), ('online', 'Online')], default='offline', help_text='Whether the event is online or offline', max_length=10),
        ),
        migrations.AddField(
            model_name='event',
            name='meeting_url',
            field=models.URLField(blank=True, help_text='Meeting URL for online events (Google Meet, Zoom, etc.)', null=True),
        ),
    ]
