"""
Django settings for radiumB project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv
from decouple import config
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env file
load_dotenv(BASE_DIR / '.env')

DEBUG = os.getenv('DEBUG',False)

# Debug environment loading
if DEBUG:
    print("Environment variables loaded:")
    print(f"  EMAIL_HOST: {os.getenv('EMAIL_HOST')}")
    print(f"  EMAIL_PORT: {os.getenv('EMAIL_PORT')}")
    print(f"  EMAIL_USE_TLS: {os.getenv('EMAIL_USE_TLS')}")
    print(f"  EMAIL_HOST_USER: {os.getenv('EMAIL_HOST_USER')}")
    print(f"  EMAIL_HOST_PASSWORD: {'*' * len(os.getenv('EMAIL_HOST_PASSWORD', '')) if os.getenv('EMAIL_HOST_PASSWORD') else None}")
    print(f"  DEFAULT_FROM_EMAIL: {os.getenv('DEFAULT_FROM_EMAIL')}")



# Cashfree Webhook Secret
CASHFREE_WEBHOOK_SECRET = os.getenv('CASHFREE_WEBHOOK_SECRET', 'changeme')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY','django-insecure-j)3n47(2k)uua3pqs)d4do_t!1zug@sb%*0fpmqj70_0jjz5ey')

# SECURITY WARNING: don't run with debug turned on in production!


# Load environment variables from .env file
load_dotenv(BASE_DIR / '.env')

ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='localhost,127.0.0.1', cast=lambda x: [i.strip() for i in x.split(',')])

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'authentication.apps.AuthConfig',
    'event.apps.EventConfig',
    'users.apps.UsersConfig',
    'users.membership.apps.MembershipConfig',
    'content.apps.ContentConfig',
    'payment.apps.PaymentConfig',
    'api_tester.apps.ApiTesterConfig',
    'academic.apps.AcademicConfig',
    'import_export',
    'corsheaders',
    'rest_framework',
    'rest_framework.authtoken',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    'allauth.socialaccount.providers.github',
    'dj_rest_auth',
    'dj_rest_auth.registration',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
]



SOCIALACCOUNT_PROVIDERS = {
    "google": {
        "APP": {
            "client_id": os.getenv("GOOGLE_CLIENT_ID"),
            "secret": os.getenv("GOOGLE_CLIENT_SECRET"),
            "key": "",
        },
        "SCOPE": [
            "profile",
            "email",
            "https://www.googleapis.com/auth/user.gender.read",
        ],
        "AUTH_PARAMS": {
            "access_type": "online",
        },
        "VERIFIED_EMAIL": True,
    },

    "github": {
        "APP": {
            "client_id": os.getenv("GITHUB_CLIENT_ID"),
            "secret": os.getenv("GITHUB_CLIENT_SECRET"),
            "key": "",
        },
        "SCOPE":[
            "user:email",

        ],
        'AUTH_PARAMS': {
            'scope': 'read:user user:email'
        },
        "VERIFIED_EMAIL": True,
    }
}

# Social account adapter
SOCIALACCOUNT_ADAPTER = 'authentication.adapters.SocialAccountAdapter'

# Site domain for password reset emails (frontend URL)
SITE_DOMAIN = os.getenv('SITE_DOMAIN', 'radium.devsrec.com')
SITE_NAME = os.getenv('SITE_NAME', 'DEVS Radium')
SITE_ID = 1

# Additional social account settings
SOCIALACCOUNT_AUTO_SIGNUP = True
ACCOUNT_UNIQUE_EMAIL = True
SOCIALACCOUNT_QUERY_EMAIL = True

# Updated account settings (replacing deprecated ones)
ACCOUNT_SIGNUP_FIELDS = ['email*', 'username*', 'password1*', 'password2*']

ACCOUNT_EMAIL_VERIFICATION = 'none'


CSRF_TRUSTED_ORIGINS = config('CSRF_TRUSTED_ORIGINS', default='http://localhost:8000,http://127.0.0.1:8000', cast=lambda x: [i.strip() for i in x.split(',')])

ROOT_URLCONF = 'radiumB.urls'

CORS_ALLOW_ALL_ORIGINS = False

CORS_ALLOWED_ORIGINS = os.getenv('CORS_ALLOWED_ORIGINS', 'http://localhost:5173,http://127.0.0.1:5173').split(',')

CORS_ALLOW_CREDENTIALS = True

CORS_ALLOW_METHODS = [
    "DELETE",
    "GET",
    "OPTIONS",
    "PATCH",
    "POST",
    "PUT",
]

CORS_ALLOW_HEADERS = [
    "accept",
    "accept-encoding",
    "authorization",
    "content-type",
    "dnt",
    "origin",
    "user-agent",
    "x-csrftoken",
    "x-requested-with",
    "x-request-timestamp",
]

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'radiumB.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

def validate_postgresql_config(db_name, db_user, db_password, db_host, db_port):
    """
    Validates PostgreSQL configuration parameters.
    
    Args:
        db_name (str): Database name
        db_user (str): Database user
        db_password (str): Database password
        db_host (str): Database host
        db_port (str): Database port
        
    Returns:
        tuple: (is_valid, missing_vars) where is_valid is bool and missing_vars is list
    """
    required_vars = {
        'DB_NAME': db_name,
        'DB_USER': db_user,
        'DB_PASSWORD': db_password,
        'DB_HOST': db_host,
    }
    
    missing_vars = [var_name for var_name, value in required_vars.items() if not value]
    
    # Validate port is numeric if provided
    if db_port and not db_port.isdigit():
        missing_vars.append('DB_PORT (must be numeric)')
    
    return len(missing_vars) == 0, missing_vars

def get_database_config():
    """
    Returns appropriate database configuration based on environment.
    
    Checks for PostgreSQL environment variables and falls back to SQLite3
    if they are missing or incomplete. Provides validation and clear error messages.
    
    Returns:
        dict: Database configuration for Django DATABASES setting
    """
    # Check if user explicitly wants to use SQLite3
    use_sqlite = os.getenv('USE_SQLITE', '').lower() in ('true', '1', 'yes')
    
    # Get PostgreSQL environment variables
    db_name = os.getenv('DB_NAME', '').strip()
    db_user = os.getenv('DB_USER', '').strip()
    db_password = os.getenv('DB_PASSWORD', '').strip()
    db_host = os.getenv('DB_HOST', '').strip()
    db_port = os.getenv('DB_PORT', '5432').strip()
    
    # Validate PostgreSQL configuration
    postgresql_valid, missing_vars = validate_postgresql_config(
        db_name, db_user, db_password, db_host, db_port
    )
    
    # Use PostgreSQL if configuration is valid and SQLite3 is not explicitly requested
    if postgresql_valid and not use_sqlite:
        if DEBUG:
            print(f"Using PostgreSQL database: {db_name} at {db_host}:{db_port}")
        return {
            'ENGINE': 'django.db.backends.postgresql_psycopg2',
            'NAME': db_name,
            'USER': db_user,
            'PASSWORD': db_password,
            'HOST': db_host,
            'PORT': db_port,
        }
    else:
        # Fall back to SQLite3
        sqlite_db_path = os.getenv('SQLITE_DB_PATH', str(BASE_DIR / 'db.sqlite3'))
        
        if DEBUG:
            if use_sqlite:
                print("Using SQLite3 database (explicitly requested)")
            elif missing_vars:
                print(f"Using SQLite3 database (PostgreSQL config incomplete: {', '.join(missing_vars)})")
            else:
                print("Using SQLite3 database (fallback)")
            print(f"SQLite3 database path: {sqlite_db_path}")
        
        return {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': sqlite_db_path,
        }

DATABASES = {
    "default": get_database_config()
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/
STATIC_ROOT = BASE_DIR / 'static'
STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'radiumB' / 'static']

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


from datetime import timedelta

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=30),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=14),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': False,

    'ALGORITHM': 'HS256',
    "SIGNING_KEY": os.getenv('JWT_SIGNING_KEY', SECRET_KEY), 
    'VERIFYING_KEY': None,
    'AUDIENCE': None,
    'ISSUER': None,
    'JWK_URL': None,
    'LEEWAY': 0,

    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    'USER_AUTHENTICATION_RULE': 'rest_framework_simplejwt.authentication.default_user_authentication_rule',

    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',
    'TOKEN_USER_CLASS': 'rest_framework_simplejwt.models.TokenUser',

    'JTI_CLAIM': 'jti',

    'SLIDING_TOKEN_REFRESH_EXP_CLAIM': 'refresh_exp',
    'SLIDING_TOKEN_LIFETIME': timedelta(minutes=5),
    'SLIDING_TOKEN_REFRESH_LIFETIME': timedelta(days=1),
}

REST_AUTH = {
    "USE_JWT": True,
    "JWT_AUTH_COOKIE": "_auth",
    "JWT_AUTH_REFRESH_COOKIE": "_refresh",
    "JWT_AUTH_HTTPONLY": False,
    "PASSWORD_RESET_USE_SITES_DOMAIN": True,
    "PASSWORD_RESET_SERIALIZER": "authentication.serializers.CustomPasswordResetSerializer",
    "PASSWORD_RESET_CONFIRM_SERIALIZER": "authentication.serializers.CustomPasswordResetConfirmSerializer",
    "REGISTER_SERIALIZER": "authentication.serializers.CustomRegisterSerializer",
}

REST_AUTH_SIGNUP_FIELDS = {
    'username': {'required': True},
    'email': {'required': True},
}

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',
        'rest_framework.parsers.FormParser',
        'rest_framework.parsers.MultiPartParser',
    ],
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle'
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '100/hour',
        'user': '1000/hour'
    },
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
    ],
}

# Media files configuration
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# File upload settings
FILE_UPLOAD_MAX_MEMORY_SIZE = 10485760  # 10MB
FILE_UPLOAD_PERMISSIONS = 0o644

# Security settings for production
if not DEBUG:
    SECURE_SSL_REDIRECT = os.getenv('SECURE_SSL_REDIRECT', 'True').lower() == 'true'
    SECURE_HSTS_SECONDS = int(os.getenv('SECURE_HSTS_SECONDS', '31536000'))  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = os.getenv('SECURE_HSTS_INCLUDE_SUBDOMAINS', 'True').lower() == 'true'
    SECURE_HSTS_PRELOAD = os.getenv('SECURE_HSTS_PRELOAD', 'True').lower() == 'true'
    SECURE_CONTENT_TYPE_NOSNIFF = os.getenv('SECURE_CONTENT_TYPE_NOSNIFF', 'True').lower() == 'true'
    SECURE_BROWSER_XSS_FILTER = os.getenv('SECURE_BROWSER_XSS_FILTER', 'True').lower() == 'true'
    X_FRAME_OPTIONS = os.getenv('X_FRAME_OPTIONS', 'DENY')
    SESSION_COOKIE_SECURE = os.getenv('SESSION_COOKIE_SECURE', 'True').lower() == 'true'
    CSRF_COOKIE_SECURE = os.getenv('CSRF_COOKIE_SECURE', 'True').lower() == 'true'
    SECURE_REFERRER_POLICY = os.getenv('SECURE_REFERRER_POLICY', 'same-origin')

# Email Configuration
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = os.getenv('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', 587))
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'True').lower() == 'true'
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD')
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', EMAIL_HOST_USER)

# Additional email settings for Gmail SMTP
EMAIL_USE_SSL = False  # Gmail uses TLS, not SSL
SERVER_EMAIL = EMAIL_HOST_USER  # Server email for error messages

# Debug email configuration in debug mode
if DEBUG:
    print("Email Configuration:")
    print(f"  EMAIL_BACKEND: {EMAIL_BACKEND}")
    print(f"  EMAIL_HOST: {EMAIL_HOST}")
    print(f"  EMAIL_PORT: {EMAIL_PORT}")
    print(f"  EMAIL_USE_TLS: {EMAIL_USE_TLS}")
    print(f"  EMAIL_HOST_USER: {EMAIL_HOST_USER}")
    print(f"  EMAIL_HOST_PASSWORD: {'*' * len(EMAIL_HOST_PASSWORD) if EMAIL_HOST_PASSWORD else None}")
    print(f"  DEFAULT_FROM_EMAIL: {DEFAULT_FROM_EMAIL}")

# Cashfree Payment Gateway Configuration
def get_cashfree_config():
    """Get Cashfree configuration from database or fallback to environment variables"""
    try:
        from payment.models import PaymentConfiguration
        config = PaymentConfiguration.get_active_config()
        if config:
            # Prioritize environment variable for environment setting to prevent URL mismatches
            env_from_env = os.getenv('CASHFREE_ENVIRONMENT', 'TEST')
            return {
                'APP_ID': config.app_id,
                'SECRET_KEY': config.secret_key,
                'ENVIRONMENT': env_from_env,  # Always use environment variable for environment
                'WEBHOOK_SECRET': config.webhook_secret,
                    'RETURN_URL': config.return_url if config.return_url else os.getenv('CASHFREE_RETURN_URL', 'https://example.com/payment/success'),
                'NOTIFY_URL': config.notify_url,
            }
    except:
        # Fallback to environment variables if database is not available
        pass

    # Fallback configuration from environment variables
    return {
        'APP_ID': os.getenv('CASHFREE_APP_ID'),
        'SECRET_KEY': os.getenv('CASHFREE_SECRET_KEY'),
        'ENVIRONMENT': os.getenv('CASHFREE_ENVIRONMENT', 'TEST'),
        'WEBHOOK_SECRET': os.getenv('CASHFREE_WEBHOOK_SECRET'),
            'RETURN_URL': os.getenv('CASHFREE_RETURN_URL', 'https://example.com/payment/success'),
        'NOTIFY_URL': os.getenv('CASHFREE_NOTIFY_URL', 'https://domain.com/api/payment/webhook/'),
    }


CASHFREE_CONFIG = get_cashfree_config()

# Validate Cashfree configuration in production
if not DEBUG and not all([
    CASHFREE_CONFIG['APP_ID'],
    CASHFREE_CONFIG['SECRET_KEY'],
    CASHFREE_CONFIG['WEBHOOK_SECRET']
]):
    raise ValueError("Cashfree configuration is incomplete. Please set CASHFREE_APP_ID, CASHFREE_SECRET_KEY, and CASHFREE_WEBHOOK_SECRET environment variables.")

# Validate Cashfree configuration for development too (with warning)
if DEBUG and not all([CASHFREE_CONFIG['APP_ID'], CASHFREE_CONFIG['SECRET_KEY']]):
    print("WARNING: Cashfree configuration is incomplete. Please set CASHFREE_APP_ID and CASHFREE_SECRET_KEY environment variables.")

# PayU Payment Gateway Configuration
def get_payu_config():
    """Get PayU configuration from environment variables"""
    return {
        'MERCHANT_KEY': os.getenv('PAYU_MERCHANT_KEY', ''),
        'MERCHANT_SALT': os.getenv('PAYU_MERCHANT_SALT', ''),
        'BASE_URL': os.getenv('PAYU_BASE_URL', 'https://test.payu.in'),
        'ENVIRONMENT': os.getenv('PAYU_ENVIRONMENT', 'TEST'),
        'SUCCESS_URL': os.getenv('PAYU_SUCCESS_URL', 'https://example.com/payment/success'),
        'FAILURE_URL': os.getenv('PAYU_FAILURE_URL', 'https://example.com/payment/failure'),
    }

PAYU_CONFIG = get_payu_config()
