# Generated by Django 5.2 on 2025-11-09 06:17
# Modified to use existing tables from users app

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0018_membership_models_conditional'),  # Depend on the last users migration that created these models
    ]

    operations = [
        # Use the existing tables from the users app by setting db_table explicitly
        migrations.CreateModel(
            name='PremiumMembershipSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Slot batch name (e.g., 'Batch 1 - November 2025')", max_length=100)),
                ('description', models.TextField(blank=True, help_text='Description of this premium slot batch')),
                ('total_slots', models.PositiveIntegerField(help_text='Total number of premium slots available')),
                ('is_open', models.BooleanField(default=False, help_text='Whether this slot is currently open for applications')),
                ('opens_at', models.DateTimeField(blank=True, help_text='When this slot opens', null=True)),
                ('closes_at', models.DateTimeField(blank=True, help_text='When this slot closes', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Premium Membership Slot',
                'verbose_name_plural': 'Premium Membership Slots',
                'ordering': ['-created_at'],
                'db_table': 'users_premiummembershipslot',  # Use existing table
            },
        ),
        migrations.CreateModel(
            name='DevsMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('membership_type', models.CharField(choices=[('basic', 'Basic DEVS Membership'), ('premium', 'Premium DEVS Membership')], default='basic', max_length=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('suspended', 'Suspended')], default='active', max_length=10)),
                ('claimed_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('premium_upgraded_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='devs_membership', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'DEVS Membership',
                'verbose_name_plural': 'DEVS Memberships',
                'ordering': ['-claimed_at'],
                'db_table': 'users_devsmembership',  # Use existing table
            },
        ),
        migrations.CreateModel(
            name='PremiumMembershipApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('waitlist', 'Waitlisted')], default='pending', max_length=10)),
                ('application_reason', models.TextField(help_text='Why do you want premium membership?')),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True, help_text='Admin notes about the application')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_premium_applications', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='premium_applications', to=settings.AUTH_USER_MODEL)),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='membership.premiummembershipslot')),
            ],
            options={
                'verbose_name': 'Premium Membership Application',
                'verbose_name_plural': 'Premium Membership Applications',
                'ordering': ['-applied_at'],
                'unique_together': {('user', 'slot')},
                'db_table': 'users_premiummembershipapplication',  # Use existing table
            },
        ),
    ]
