# Generated by Django 5.2.7 on 2025-11-02 19:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_event_gateway_credentials_event_gateway_options'),
        ('payment', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentconfiguration',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Payment Configuration', 'verbose_name_plural': 'Payment Configurations'},
        ),
        migrations.AddField(
            model_name='paymentconfiguration',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='User who last updated this configuration', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_config_updates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='payment',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='paymentconfiguration',
            name='environment',
            field=models.CharField(choices=[('TEST', 'Test Environment'), ('PRODUCTION', 'Production Environment')], default='TEST', help_text='Cashfree environment', max_length=20),
        ),
        migrations.AlterField(
            model_name='paymentconfiguration',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this configuration is currently active'),
        ),
        migrations.AlterField(
            model_name='paymentconfiguration',
            name='notify_url',
            field=models.URLField(default='https://domain.com/api/payment/webhook/', help_text='Webhook URL for payment notifications'),
        ),
        migrations.AlterField(
            model_name='paymentconfiguration',
            name='return_url',
            field=models.URLField(default='http://localhost:3000/payment/success', help_text='URL to redirect after payment completion'),
        ),
        migrations.AlterField(
            model_name='paymentconfiguration',
            name='webhook_secret',
            field=models.CharField(blank=True, help_text='Webhook secret for signature verification', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='paymentwebhook',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='paymentwebhook',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='webhooks', to='payment.payment'),
        ),
        migrations.AlterUniqueTogether(
            name='payment',
            unique_together={('user', 'event')},
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['order_id'], name='payment_pay_order_i_211f02_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['cf_order_id'], name='payment_pay_cf_orde_003ef9_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status'], name='payment_pay_status_124d3d_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['user', 'status'], name='payment_pay_user_id_94fc9f_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['user', 'event'], name='payment_pay_user_id_12b558_idx'),
        ),
    ]
