# Generated by Django 5.2.7 on 2025-10-20 04:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(blank=True, help_text='Optional display name', max_length=255)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('degree', models.CharField(blank=True, choices=[('B.E', 'Bachelor of Engineering'), ('B.Tech', 'Bachelor of Technology'), ('M.E', 'Master of Engineering'), ('M.Tech', 'Master of Technology'), ('MBA', 'Master of Business Administration'), ('Ph.D', 'Doctor of Philosophy')], max_length=10)),
                ('department', models.CharField(blank=True, choices=[('Aero', 'Aeronautical Engineering'), ('Auto', 'Automobile Engineering'), ('BME', 'Biomedical Engineering'), ('Civil', 'Civil Engineering'), ('CSD', 'Computer Science & Design'), ('CSE', 'Computer Science & Engineering'), ('CSE_CS', 'Computer Science & Engineering (Cyber Security)'), ('EEE', 'Electrical & Electronics Engineering'), ('ECE', 'Electronics & Communication Engineering'), ('Mech', 'Mechanical Engineering'), ('MCT', 'Mechatronics Engineering'), ('Robotics', 'Robotics and Automation'), ('AIDS', 'Artificial Intelligence & Data Science'), ('AIML', 'Artificial Intelligence & Machine Learning'), ('Biotech', 'Bio Technology'), ('Chem', 'Chemical Engineering'), ('CSBS', 'Computer Science and Business Systems'), ('FT', 'Food Technology'), ('IT', 'Information Technology'), ('Avionics', 'Avionics'), ('CommSys', 'Communication Systems'), ('EngDesign', 'Engineering Design'), ('Embedded', 'Embedded System Technologies'), ('MedElec', 'Medical Electronics'), ('CSE_PG', 'Computer Science & Engineering (PG)'), ('BioTech_PG', 'Bio-Technology (PG)'), ('DS', 'Data Science'), ('MBA', 'Master of Business Administration'), ('PhD_Biotech', 'Ph.D. Biotechnology'), ('PhD_BME', 'Ph.D. Biomedical Engineering'), ('PhD_Chem', 'Ph.D. Chemistry'), ('PhD_CSE', 'Ph.D. Computer Science and Engineering'), ('PhD_ECE', 'Ph.D. Electronics and Communication Engineering'), ('PhD_EEE', 'Ph.D. Electrical and Electronics Engineering'), ('PhD_Maths', 'Ph.D. Mathematics'), ('PhD_Mech', 'Ph.D. Mechanical Engineering')], max_length=255)),
                ('rollno', models.CharField(blank=True, help_text='Student roll number', max_length=20)),
                ('phone_number', models.CharField(blank=True, max_length=15)),
                ('college_name', models.CharField(default='Rajalakshmi Engineering College', max_length=255)),
                ('profile_picture', models.URLField(blank=True, help_text='Social profile picture URL')),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
    ]
