# Generated by Django 5.2.7 on 2025-10-21 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userprofile_year_alter_userprofile_degree_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='year',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
