# Generated by Django 5.2.7 on 2025-11-02 13:23

from django.db import migrations, models
from django.core.exceptions import FieldDoesNotExist


def migrate_userprofile_fields_forward(apps, schema_editor):
    """
    Safely migrate UserProfile fields to avoid conflicts in containerized environments.
    This function handles adding/removing fields defensively.
    """
    UserProfile = apps.get_model('users', 'UserProfile')

    # Try to remove is_staff if it exists
    try:
        schema_editor.remove_field(UserProfile, UserProfile._meta.get_field('is_staff'))
    except (FieldDoesNotExist, AttributeError):
        # Field doesn't exist, skip
        pass

    # Add is_eventStaff if it doesn't exist
    try:
        UserProfile._meta.get_field('is_eventStaff')
    except FieldDoesNotExist:
        schema_editor.add_field(
            UserProfile,
            models.BooleanField(default=False, name='is_eventStaff')
        )

    # Add is_qr_scanner if it doesn't exist
    try:
        UserProfile._meta.get_field('is_qr_scanner')
    except FieldDoesNotExist:
        schema_editor.add_field(
            UserProfile,
            models.BooleanField(default=False, help_text='Can access QR scanner functionality', name='is_qr_scanner')
        )

    # Add is_superuser if it doesn't exist
    try:
        UserProfile._meta.get_field('is_superuser')
    except FieldDoesNotExist:
        schema_editor.add_field(
            UserProfile,
            models.BooleanField(default=False, name='is_superuser')
        )


def migrate_userprofile_fields_reverse(apps, schema_editor):
    """
    Reverse migration for UserProfile fields
    """
    UserProfile = apps.get_model('users', 'UserProfile')

    # Remove the added fields
    try:
        schema_editor.remove_field(UserProfile, UserProfile._meta.get_field('is_eventStaff'))
    except FieldDoesNotExist:
        pass

    try:
        schema_editor.remove_field(UserProfile, UserProfile._meta.get_field('is_qr_scanner'))
    except FieldDoesNotExist:
        pass

    try:
        schema_editor.remove_field(UserProfile, UserProfile._meta.get_field('is_superuser'))
    except FieldDoesNotExist:
        pass

    # Add back is_staff
    try:
        UserProfile._meta.get_field('is_staff')
    except FieldDoesNotExist:
        schema_editor.add_field(
            UserProfile,
            models.BooleanField(default=False, name='is_staff')
        )


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_userprofile_year'),
    ]

    operations = [
        migrations.RunPython(migrate_userprofile_fields_forward, migrate_userprofile_fields_reverse),
    ]
