# Generated by Django 5.2.7 on 2025-10-17 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_userprofile_is_staff_and_more'),
    ]

    operations = [
    ]
