# Generated by Django 5.2.7 on 2025-10-18 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_merge_20251017_1230'),
    ]

    operations = [
    ]
