# Generated by Django 5.2.7 on 2025-10-19 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_merge_20251018_0940'),
    ]

    operations = [
    ]
