# Generated by Django 5.2.7 on 2025-10-19 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_merge_20251019_1214'),
    ]

    operations = [
    ]
