# Generated by Django 5.2.7 on 2025-10-19 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_merge_20251019_1559'),
    ]

    operations = [
    ]
