# Generated by Django 5.2.7 on 2025-10-20 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_merge_20251020_0237'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='year',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]