# Generated by Django 5.2.7 on 2025-10-22 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_userprofile_year'),
        ('users', '0013_userprofile_year'),
    ]

    operations = [
    ]
