# Generated by Django 5.2.7 on 2025-10-29 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_merge_20251022_1706'),
    ]

    operations = [
        # Field rename was done manually in database
        # is_qr_staff was renamed to is_qr_scanner to match model definition
    ]
