# Generated by Django 5.2.7 on 2025-11-02 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_userprofile_is_staff_and_more'),
        ('users', '0015_add_is_qr_staff_field'),
    ]

    operations = [
    ]
