# Generated by Django 5.2.7 on 2025-11-08 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_premiummembershipslot_alter_userprofile_year_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text="Department code (e.g., 'CSE', 'ECE')", max_length=50, unique=True)),
                ('full_name', models.CharField(help_text='Full department name', max_length=255)),
                ('category', models.CharField(choices=[('UG', 'Undergraduate'), ('PG', 'Postgraduate'), ('PhD', 'Doctoral')], default='UG', help_text='Department category', max_length=50)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this department is currently active')),
                ('order', models.IntegerField(default=0, help_text='Display order (lower numbers appear first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
                'ordering': ['category', 'order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text="Year code (e.g., '1', '2', 'PG1')", max_length=10, unique=True)),
                ('display_name', models.CharField(help_text="Display name (e.g., '1st Year', '2nd Year')", max_length=50)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this year option is currently active')),
                ('order', models.IntegerField(default=0, help_text='Display order (lower numbers appear first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Academic Year',
                'verbose_name_plural': 'Academic Years',
                'ordering': ['order', 'code'],
            },
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='department',
            field=models.CharField(blank=True, help_text='Department code', max_length=255),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='year',
            field=models.CharField(blank=True, help_text='Academic year', max_length=20),
        ),
    ]
