# Generated by Django 5.2.7 on 2025-11-08 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_department_year_alter_userprofile_department_and_more'),
        ('users', '0018_membership_models_conditional'),
    ]

    operations = [
    ]
